### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by TheDiamondYT1** [voxelwind/voxelwind-site#1]
Delete this repository, now :)

**Comment by TheDiamondYT1** [comment]
I'm right though. It's an empty repo that has had nothing added in 7 months @minecrafter

**Comment by karpovichv** [comment]
We can decide without your help, ok?

**Comment by TheDiamondYT1** [comment]
Who put you in charge? You don't need to be such a dick. You're here to continue voxelwind development.

**Comment by Tee7even** [comment]
Believe it or not, but _Tux_ put _us_ in charge. That is: @fromgate, @pub4game and me. The team of former nukkit.ru. 
And you know what? I'm not *yet* being even _a slightest_ dick. I'm just _friendly reminding you_, that you are not someone to give orders here.
